on:
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  # login using the azure/login action
  managed-identity-azure-login:
    runs-on: ubuntu-latest
    steps:
      - uses: azure/login@v2
        with:
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          allow-no-subscriptions: true

  # login using az cli
  managed-identity-cli-login:
    runs-on: ubuntu-latest
    steps:
      - run: |
          az login                                 \
            --service-principal                    \
            --allow-no-subscriptions               \
            --username ${{ vars.AZURE_CLIENT_ID }} \
            --tenant   ${{ vars.AZURE_TENANT_ID }} \
            --federated-token "$(curl --silent --header "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=api://AzureADTokenExchange" | jq --raw-output '.value')"

      - run: az account clear && az logout
